name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ vars.CONTAINER_IMAGE_NAME_BACKEND }}:$CI_COMMIT_SHORT_SHA

    - name: Login to Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Login to ACR
      run: az acr login --name ${{ vars.CONTAINER_REGISTRY_NAME }}

    - name: Remote tag image
      run: docker tag ${{ vars.CONTAINER_IMAGE_NAME_BACKEND }}:$CI_COMMIT_SHORT_SHA ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_IMAGE_NAME_BACKEND }}:$CI_COMMIT_SHORT_SHA

    - name: Push image to ACR
      run: docker push ${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io/${{ vars.CONTAINER_IMAGE_NAME_BACKEND }}:$CI_COMMIT_SHORT_SHA
