name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
      id-token: write
      contents: read

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      version: ${{ github.sha }}
    secrets: inherit