name: Backend pytest

on:
  push:
    branches: [ "fastapi-groundwork" ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install poetry
        uses: snok/install-poetry@v1.2.0

      - name: Install dependencies
        run: poetry install

      - name: Run backend test
        run: poetry run python -m pytest
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: action_test

        
